'use strict';
const lessons = {
cache: {
 label:'01 / PERFORMANCE', title:'Caching is a consistency decision.', intro:'A cache saves repeated work. The design question is how much staleness your users can tolerate—and how the system behaves when the cache disappears.',
 flow:'Client <span>→</span> API <span>→</span> Cache <span>→ miss →</span> Database',
 steps:['Look up the item in the cache. A hit can avoid a database read.','On a miss, fetch from the database and populate the cache with a time-to-live (TTL).','On a write, commit to the database, then invalidate the affected cache key. This reduces staleness; concurrent reads and writes can still race.'],
 use:['Repeated reads of popular items where modest staleness is acceptable.','Expensive computations whose results can be reused.','Start by defining freshness requirements and measuring hit rate, miss latency, and database load.'],
 trade:['Cache-aside keeps the application in control, but adds failure paths and invalidation logic.','A TTL limits how long an entry survives; it does not guarantee a maximum lag from every database update under all races.','A cache is not the authority for balances, permissions, or inventory reservations unless your consistency protocol explicitly makes that safe.'],
 scenarios:[['Normal traffic','Popular reads hit the cache. Watch both hit rate and tail latency: a high average hit rate can hide slow misses.'],['Cache outage','Reads fall back to the database only within a safe load budget. Use timeouts, concurrency limits, and load shedding; blindly forwarding every request can overload the database.'],['Hot key expires','Many clients miss at once. Coalesce concurrent requests for the same key, add expiry jitter across keys, and consider serving a stale value if the product permits it.']],
 drill:'A popular item changes price while thousands of users read it. How would you keep the product page fast without trusting a stale price at checkout?',
 answer:'Cache the display data with an explicit freshness policy. Treat checkout as a separate correctness path: validate the authoritative price and availability when creating the order. Explain invalidation races, what happens during cache failure, and why a cached page is not proof of the final purchase price.',
 sources:[['Redis: cache-aside','https://redis.io/docs/latest/develop/use-cases/cache-aside/']]
},
queue:{
 label:'02 / RELIABILITY',title:'A queue moves work, not responsibility.',intro:'Asynchronous processing lets the request finish before expensive work completes. You still need a durable handoff, retry policy, and an honest user-visible status.',
 flow:'API <span>→</span> Durable queue <span>→</span> Worker <span>→</span> Result',
 steps:['Validate the request and assign a stable job or operation identifier.','Durably record or enqueue the work before reporting acceptance. If both a database write and message publication are needed, consider a transactional outbox.','Process the task, persist its result, then acknowledge according to the broker’s semantics. Expose a status endpoint or completion event.'],
 use:['Email delivery, image processing, exports, and other work that does not need to finish inside the request.','Buffer short bursts when workers can catch up afterward. A queue cannot solve a permanently insufficient processing rate.','Measure oldest message age, processing rate, failures, and backlog—not just queue length.'],
 trade:['At-least-once delivery can repeat messages. Make side effects idempotent with a durable operation key or an equivalent atomic protocol.','Ordering is scoped to your broker configuration. Global ordering may reduce parallelism; use per-entity ordering where needed.','A retry policy needs limits and backoff. A dead-letter queue needs inspection and a safe replay process.'],
 scenarios:[['Normal traffic','Workers consume jobs and report completion. Users see accepted, processing, or completed states rather than a premature success message.'],['Worker crashes','A crash after a side effect but before acknowledgement can cause redelivery. Use a durable deduplication record, atomic state transition, or downstream idempotency key to prevent repeating that effect.'],['Backlog grows','If arrival rate exceeds processing capacity, waiting time keeps growing. Scale within downstream limits, throttle producers, or shed optional work. Alert on job age relative to the promised completion time.']],
 drill:'A worker charges a customer, then crashes before acknowledging the message. What makes a retry safe?',
 answer:'Reuse the same operation identifier with the payment provider’s idempotency mechanism. Persist and reconcile the operation state rather than assuming a timeout means failure. A local “processed” flag alone is not enough if it cannot be committed atomically with the external charge. Explain how uncertain results are resolved before issuing a new charge.',
 sources:[['AWS Builders’ Library: safe retries','https://aws.amazon.com/builders-library/making-retries-safe-with-idempotent-APIs/'],['AWS: transactional outbox','https://docs.aws.amazon.com/prescriptive-guidance/latest/cloud-design-patterns/transactional-outbox.html']]
},
rate:{
 label:'03 / PROTECTION',title:'Rate limits express a capacity policy.',intro:'Decide who gets how much capacity, over which interval, and what happens when the limiter fails. The algorithm follows those requirements.',
 flow:'Request <span>→</span> Identity + policy <span>→</span> Limiter <span>→ allow →</span> API',
 steps:['Choose the limiting identity: account, API key, tenant, IP address, or a combination. Shared IPs can represent many legitimate users.','Evaluate a policy with an atomic counter or token operation. With multiple API replicas, decide whether coordination is needed.','Reject excess requests with HTTP 429 where appropriate. Document retry behavior and use Retry-After when the server can provide a meaningful delay.'],
 use:['Protect shared resources and limit abusive or accidental request floods.','Enforce tenant fairness or API usage policies.','Combine rate limits with concurrency limits for slow operations: request rate alone does not bound in-flight work.'],
 trade:['A fixed window is simple but can allow a burst at the boundary. A sliding window gives a different time-based policy at a higher state or computation cost.','A token bucket permits bursts up to bucket capacity and replenishes at a configured rate. That is not the same as an exact rolling-window quota.','A shared limiter adds coordination and availability concerns. Per-replica limits are simpler but the fleet-wide allowance changes with replica count.'],
 scenarios:[['Normal traffic','An illustrative token bucket refills at 10 tokens per second and holds 20. A request consumes one token; the bucket allows a short burst and then settles toward its refill rate. These are example values, not production sizing.'],['Traffic spike','Reject excess work before expensive processing. Bound upstream connections too: a rate limiter inside the application cannot by itself stop every network-level flood.'],['Limiter unavailable','Choose fail-open or fail-closed by endpoint risk. A public read may allow bounded fallback traffic; a sensitive or expensive operation may reject it. Keep local concurrency protection either way.']],
 drill:'Your API grows from two replicas to ten. Each replica independently allows 100 requests per second per tenant. What changes?',
 answer:'The theoretical aggregate allowance rises from 200 to 1,000 requests per second if requests reach all replicas. Uneven routing creates further inconsistency. If the quota must apply across the fleet, coordinate state, allocate bounded budgets, or use a centralized enforcement point. Specify the allowed error and failure behavior instead of assuming a local counter is global.',
 sources:[['Redis: rate limiting','https://redis.io/tutorials/howtos/ratelimiting/'],['RFC 6585: HTTP 429','https://www.rfc-editor.org/rfc/rfc6585#section-4']]
}
};
const panel=document.getElementById('lesson-panel');
function list(items){return '<ul>'+items.map(x=>'<li>'+x+'</li>').join('')+'</ul>';}
function render(topic,updateHash=false){
 if(!lessons[topic])topic='cache';const l=lessons[topic];
 document.querySelectorAll('[data-topic]').forEach(b=>{const selected=b.dataset.topic===topic;b.setAttribute('aria-selected',String(selected));b.tabIndex=selected?0:-1;});
 panel.setAttribute('aria-labelledby','tab-'+topic);
 panel.innerHTML=`<div class="lesson-head"><div><p class="eyebrow">${l.label} · DECISION CARD</p><h2>${l.title}</h2></div><p>${l.intro}</p></div><div class="flow" aria-label="Request flow">${l.flow}</div><div class="lesson-grid"><section class="lesson-box"><h3>Follow the request</h3><ol>${l.steps.map(x=>'<li>'+x+'</li>').join('')}</ol></section><section class="lesson-box"><h3>When it earns its complexity</h3>${list(l.use)}</section><section class="lesson-box wide"><h3>The tradeoffs to explain</h3>${list(l.trade)}</section><section class="lesson-box wide"><h3>Change the conditions</h3><p>Explore how the design behaves. These are explanatory scenarios, not a live benchmark.</p><div class="scenario-controls">${l.scenarios.map((s,i)=>`<button data-scenario="${i}" aria-pressed="${i===0}">${s[0]}</button>`).join('')}</div><div class="scenario-result" aria-live="polite">${l.scenarios[0][1]}</div></section><section class="lesson-box wide"><h3>Practice the decision</h3><p>${l.drill}</p><details><summary>Reveal an explained answer</summary><p class="answer">${l.answer}</p></details></section></div><p class="sources">Further reading: ${l.sources.map(s=>`<a href="${s[1]}" target="_blank" rel="noopener noreferrer">${s[0]} ↗</a>`).join(' · ')}</p>`;
 panel.querySelectorAll('[data-scenario]').forEach(b=>b.addEventListener('click',()=>{panel.querySelectorAll('[data-scenario]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));panel.querySelector('.scenario-result').textContent=l.scenarios[Number(b.dataset.scenario)][1];}));
 if(updateHash)history.replaceState(null,'','#'+topic);
}
document.querySelectorAll('[data-topic]').forEach(b=>b.addEventListener('click',()=>render(b.dataset.topic,true)));
document.querySelectorAll('[data-open]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();render(a.dataset.open,true);document.getElementById('lesson').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});panel.focus({preventScroll:true});}));
document.querySelector('.tabs').addEventListener('keydown',e=>{const keys=['ArrowRight','ArrowLeft','Home','End'];if(!keys.includes(e.key))return;e.preventDefault();const tabs=[...document.querySelectorAll('[data-topic]')];let i=tabs.indexOf(document.activeElement);if(i<0)i=0;i=e.key==='Home'?0:e.key==='End'?tabs.length-1:(i+(e.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;render(tabs[i].dataset.topic,true);tabs[i].focus();});
document.getElementById('print').addEventListener('click',()=>{panel.querySelector('details').open=true;window.print();});
window.addEventListener('hashchange',()=>{const topic=location.hash.slice(1);if(lessons[topic]){render(topic);document.getElementById('lesson').scrollIntoView();}});
const initial=location.hash.slice(1);render(initial);if(lessons[initial])requestAnimationFrame(()=>document.getElementById('lesson').scrollIntoView());
